# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "att_wrapper"
  s.version = "0.1.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Harrington"]
  s.date = "2013-01-05"
  s.description = "A simple interface for using the AT&T Platform APIs.  All you need is your client_id and client and a bit of code."
  s.email = "rh8730@att.com"
  s.files = [
    ".document",
    ".gitignore",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "att_wrapper.gemspec",
    "lib/att_wrapper.rb",
    "test/helper.rb",
    "test/test_payments.rb"
  ]
  s.homepage = "https://github.com/attdevsupport/2013DevSummitExamples/tree/master/Payment"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A wrapper class for the AT&T Platform APIs that hides all the technical details"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

