source "http://rubygems.org"
# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem "minitest"
  gem "shoulda", ">= 0"
  gem "rdoc", "~> 3.12"
  gem "bundler", "~> 1.2.0"
  gem "jeweler", "~> 1.8.4"
  gem "sinatra", :require => "sinatra/base"
  gem "thin", "~>1.5"
  gem "htmlentities", "~>4.3"
  gem "haml", "~>3.1"
end
