source :rubygems
gem "att_wrapper", "0.1.0.pre", :git => "https://github.com/attdevsupport/2013DevSummitExamples.git"
gem "data_mapper"
gem "dm-postgres-adapter"
gem "dm-types"
gem "dm-validations"
gem "haml", "~>3.1"
gem "htmlentities", "~>4.3"
gem "json"
gem "koala"
gem "pg"
gem "sinatra", :require => "sinatra/base"
gem "thin", "~>1.5"

